name: PR Validation 🩷💙
on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: '5.4'

      - name: Install LuaRocks
        run: |
          wget https://luarocks.org/releases/luarocks-3.9.2.tar.gz
          tar zxpf luarocks-3.9.2.tar.gz
          cd luarocks-3.9.2
          LUA_PATH=$(which lua)
          LUA_DIR=$(dirname $(dirname $LUA_PATH))
          ./configure --with-lua=$LUA_DIR --with-lua-include=$LUA_DIR/include --prefix=$HOME/.local
          make
          make install
          cd ..
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          luarocks install --local busted
          luarocks install --local luacov
          luarocks install --local luacov-console
          luarocks install --local luacov-html

      - name: Run tests
        run: |
          $HOME/.local/bin/busted -v --coverage

      - name: Generate coverage report
        run: |
          $HOME/.local/bin/luacov
          $HOME/.local/bin/luacov-console

      - name: Check coverage
        run: |
          $HOME/.local/bin/luacov-html
          # Qui puoi aggiungere controlli sulla copertura del codice
          # Ad esempio, fallire se la copertura è inferiore a una certa percentuale
